// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKT8UmkQuFc33CzeLcTfyO4IwaUNtWTnY',
    appId: '1:397813438387:web:ecd154161c69c7ccf35dc6',
    messagingSenderId: '397813438387',
    projectId: 'fulminant-c',
    authDomain: 'fulminant-c.firebaseapp.com',
    storageBucket: 'fulminant-c.firebasestorage.app',
    measurementId: 'G-NNB2NXCFSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE2PWFCa-H0GEBsFUmSt1nBDv0as10wG4',
    appId: '1:397813438387:android:17c4125ac3a75650f35dc6',
    messagingSenderId: '397813438387',
    projectId: 'fulminant-c',
    storageBucket: 'fulminant-c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyExample_iOS_Key_Replace_With_Actual_Key',
    appId: '1:123456789:ios:abcd1234',
    messagingSenderId: '123456789',
    projectId: 'fulminant-learning-app',
    storageBucket: 'fulminant-learning-app.appspot.com',
    iosBundleId: 'io.github.hetti219.fulminantC',
  );
}